
apiVersion: apps/v1
kind: Deployment
metadata:
 name: capstone
spec:
 replicas: 3
 selector:
  matchLabels:
   app: capstone
 template:
  metadata:
   labels:
    app: capstone
  spec:
   containers:
    - name: capstone
      image: jjdockerdev/docker-image
      ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 500m
            memory: 300Mi
