
apiVersion: apps/v1
kind: Deployment
metadata:
 name: simpli_capstone_project
spec:
 replicas: 3
 selector:
  matchLabels:
   app: simpli_capstone_project
 template:
  metadata:
   labels:
    app: simpli_capstone_project
  spec:
   containers:
    - name: c1
      image: jjdockerdev/docker-image